# Generated by Django 3.0.3 on 2020-03-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3000)),
                ('root', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pages',
            name='dog1_image',
            field=models.ImageField(blank=True, upload_to='pages'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='dog1_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='pages',
            name='dog2_image',
            field=models.ImageField(blank=True, upload_to='pages'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='dog2_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='pages',
            name='dog3_image',
            field=models.ImageField(blank=True, upload_to='pages'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='dog3_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='pages',
            name='human1_image',
            field=models.ImageField(blank=True, upload_to='pages'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='human1_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='pages',
            name='human2_image',
            field=models.ImageField(blank=True, upload_to='pages'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='human2_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
